apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostname
  template:
    metadata:
      name: hostname
      labels:
        app: hostname
    spec:
      containers:
      - image: kbzjung359/kia-hostname:v1
        name: nodejs
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hostname
spec:
  type: NodePort
  selector:
    app: hostname
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30123
