apiVersion: v1
kind: Pod
metadata:
  name: hostname-manual-nogpu
  labels:
    creation_method: manual
    env: prod
    gpu: "false"
spec:
  nodeSelector: # 파드가 gpu=false 라벨이 설정된 노드에 예약되도록 지정
    gpu: "false"
  containers:
  - image: kbzjung359/kia-hostname
    name: hostname
    ports:
    - containerPort: 8080
      protocol: TCP