apiVersion: v1
kind: Pod
metadata:
  name: hostname-manual-nogpu
  labels:
    creation_method: manual
    env: prod
    gpu: "false"
  namespace: somespace # 파드의 네임스페이스 설정
spec:
  nodeSelector:
    gpu: "false"
  containers:
  - image: kbzjung359/kia-hostname
    name: hostname
    ports:
    - containerPort: 8080
      protocol: TCP