apiVersion: v1
kind: ReplicationController
metadata:
  name: hostname-rc
spec:
  replicas: 2 # 복제본 수 설정
  selector: # RC의 관리 범위 지정
    app: hostname
  template: # 생성할 파드를 설정
    metadata:
      labels: 
        app: hostname # 라벨 지정
    spec:
      containers:
      - name: hostname
        image: kbzjung359/kia-hostname
        ports:
        - containerPort: 8080