apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
  - image: kbzjung359/kia-unhealthy
    name: unhealthy
    livenessProbe: # 활성 프로브 설정
      httpGet: # HTTP GET Probe
        path: / # '/' 경로로 GET 요청
        port: 8080 # 8080 포트로 GET 요청